# Column Transformer

In [4]:
import numpy as np
import pandas as pd


from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import  OrdinalEncoder

In [2]:
df = pd.read_csv(r"/Users/rahulkumarghosh/Documents/100_DAYS_ML/Day_28/covid_toy.csv")

In [5]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [6]:
df["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [7]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test , y_train, y_test = train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)

In [11]:
X_train

    age  gender  fever   cough       city
91   38    Male    NaN    Mild      Delhi
52   47  Female  100.0  Strong  Bangalore
85   16  Female  103.0    Mild  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
89   46    Male  103.0  Strong  Bangalore
30   15    Male  101.0    Mild      Delhi
78   11    Male  100.0    Mild  Bangalore
45   72    Male   99.0    Mild  Bangalore
50   19    Male  101.0    Mild      Delhi

[80 rows x 5 columns]

In [12]:
X_test

    age  gender  fever   cough       city
37   55    Male  100.0    Mild    Kolkata
47   18  Female  104.0    Mild  Bangalore
32   34  Female  101.0  Strong      Delhi
74   34  Female  104.0  Strong      Delhi
43   22  Female   99.0    Mild  Bangalore
41   82    Male    NaN    Mild    Kolkata
83   17  Female  104.0    Mild    Kolkata
25   23    Male    NaN    Mild     Mumbai
24   13  Female  100.0  Strong    Kolkata
58   23    Male   98.0  Strong     Mumbai
7    20  Female    NaN  Strong     Mumbai
57   49  Female   99.0  Strong  Bangalore
11   65  Female   98.0    Mild     Mumbai
73   34    Male   98.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata
33   26  Female   98.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
29   34  Female    NaN  Strong     Mumbai
8    19  Female  100.0  Strong  Bangalore
61   81  Female   98.0  Strong     Mumbai

# Aam Zindagi

In [15]:
si = SimpleImputer()
X_train_feaver = si.fit_transform(X_train[["fever"]])

X_test_feaver = si.fit_transform(X_test[["fever"]])

In [18]:
X_train_feaver.shape

(80, 1)

In [20]:
df["cough"].unique()

array(['Mild', 'Strong'], dtype=object)

In [25]:
oe = OrdinalEncoder(categories=[["Mild", "Strong"]])

X_train_cough = oe.fit_transform(X_train[["cough"]])
X_test_cough = oe.fit_transform(X_test[["cough"]])

In [27]:
X_train_cough.shape

(80, 1)

In [37]:
ohe = OneHotEncoder(drop="first")
X_train_gender_city = ohe.fit_transform(X_train[["gender","city"]])

X_test_gender_city = ohe.fit_transform(X_test[["gender","city"]])

X_train_gender_city.shape

(80, 4)

In [41]:
X_train_age = X_train.drop(columns=["gender","fever","cough","city"])
X_test_age = X_test.drop(columns=["gender","fever","cough","city"])

X_train_age.shape

(80, 1)

In [44]:
# X_train_transformed = np.concatenate((X_train_age,X_train_feaver,X_train_gender_city,X_train_cough),axis=1)
# X_test_transformed = np.concatenate((X_test_age,X_test_feaver,X_test_gender_city,X_test_cough),axis=1)

import numpy as np

X_train_transformed = np.concatenate(
    (X_train_age, X_train_feaver, X_train_gender_city, X_train_cough),
    axis=1
)

X_test_transformed = np.concatenate(
    (X_test_age, X_test_feaver, X_test_gender_city, X_test_cough),
    axis=1
)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 2 has 0 dimension(s)

In [45]:
print(type(X_train_age))
print(type(X_train_feaver))
print(type(X_train_gender_city))
print(type(X_train_cough))

print(X_train_age.shape)
print(X_train_feaver.shape)
print(X_train_cough.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
<class 'scipy.sparse._csr.csr_matrix'>
<class 'numpy.ndarray'>
(80, 1)
(80, 1)
(80, 1)

In [46]:
X_train_gender_city = X_train_gender_city.toarray()
X_test_gender_city = X_test_gender_city.toarray()

In [47]:
X_train_age = X_train_age.values
X_test_age = X_test_age.values

In [48]:
import numpy as np

X_train_transformed = np.concatenate(
    (X_train_age, X_train_feaver, X_train_gender_city, X_train_cough),
    axis=1
)

X_test_transformed = np.concatenate(
    (X_test_age, X_test_feaver, X_test_gender_city, X_test_cough),
    axis=1
)

In [49]:
X_train_transformed.shape

(80, 7)

# Mentos Zindagi

In [50]:
from sklearn.compose import ColumnTransformer

In [57]:
transformer = ColumnTransformer(
    transformers=[
        ("tnf1", SimpleImputer(strategy="most_frequent"), ["fever"]),
        ("tnf2", OrdinalEncoder(categories=[["Mild", "Strong"]]), ["cough"]),
        ("tnf3", OneHotEncoder(sparse_output=False, drop="first"), ["gender", "city"])
    ],
    remainder="passthrough"
)

In [58]:
transformer.fit_transform(X_train)

array([[101.,   0.,   1.,   1.,   0.,   0.,  38.],
       [100.,   1.,   0.,   0.,   0.,   0.,  47.],
       [103.,   0.,   0.,   0.,   0.,   0.,  16.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [104.,   0.,   1.,   0.,   0.,   0.,  51.],
       [102.,   0.,   1.,   0.,   1.,   0.,   5.],
       [104.,   0.,   0.,   0.,   1.,   0.,   6.],
       [ 98.,   0.,   0.,   1.,   0.,   0.,  80.],
       [101.,   0.,   0.,   0.,   0.,   1.,  19.],
       [101.,   0.,   0.,   0.,   0.,   0.,  84.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [103.,   0.,   0.,   0.,   1.,   0.,  69.],
       [101.,   0.,   1.,   1.,   0.,   0.,  42.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [100.,   0.,   0.,   0.,   1.,   0.,   5.],
       [101.,   1.,   0.,   1.,   0.,   0.,  68.],
       [103.,   0.,   1.,   0.,   1.,   0.,  83.],
       [101.,   1.,   1.,   0.,   1.,   0.,  71.],
       [102.,   1.,   0.,   0.,   0.,   0.,  82.],
       [100.,   0.,   1.,   0.,   0.,   0.,  80.],
       [102.,   0.,   1.,   0.,   0.,   1.,  74.],
       [103.,   0.,   0.,   0.,   1.,   0.,  48.],
       [ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [102.,   1.,   1.,   1.,   0.,   0.,  20.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [ 98.,   0.,   1.,   0.,   0.,   0.,  73.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,   5.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [103.,   0.,   0.,   0.,   1.,   0.,  50.],
       [101.,   0.,   0.,   1.,   0.,   0.,  49.],
       [104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [ 98.,   0.,   1.,   1.,   0.,   0.,  83.],
       [101.,   0.,   0.,   0.,   0.,   1.,  65.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [102.,   1.,   0.,   0.,   0.,   0.,  24.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  65.],
       [104.,   1.,   0.,   0.,   0.,   0.,  56.],
       [ 99.,   1.,   0.,   1.,   0.,   0.,  59.],
       [ 99.,   1.,   0.,   0.,   1.,   0.,  25.],
       [101.,   0.,   0.,   0.,   0.,   0.,  20.],
       [104.,   0.,   0.,   0.,   0.,   0.,  12.],
       [101.,   0.,   0.,   1.,   0.,   0.,  75.],
       [104.,   0.,   1.,   0.,   0.,   0.,  25.],
       [101.,   0.,   0.,   0.,   1.,   0.,   8.],
       [103.,   0.,   1.,   0.,   1.,   0.,  60.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [102.,   1.,   0.,   1.,   0.,   0.,  33.],
       [102.,   0.,   1.,   0.,   0.,   0.,  64.],
       [101.,   1.,   1.,   0.,   0.,   0.,  14.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [ 98.,   0.,   1.,   0.,   1.,   0.,  24.],
       [104.,   0.,   1.,   0.,   1.,   0.,  16.],
       [102.,   1.,   0.,   0.,   1.,   0.,  82.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  71.],
       [101.,   0.,   0.,   1.,   0.,   0.,  64.],
       [101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  31.],
       [102.,   0.,   0.,   1.,   0.,   0.,  49.],
       [101.,   1.,   1.,   0.,   0.,   0.,  47.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [ 98.,   1.,   0.,   1.,   0.,   0.,  40.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [104.,   0.,   1.,   0.,   0.,   1.,  42.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  14.],
       [100.,   0.,   0.,   0.,   1.,   0.,  19.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  69.],
       [101.,   1.,   1.,   0.,   1.,   0.,  79.],
       [101.,   1.,   0.,   0.,   0.,   0.,  42.],
       [104.,   1.,   0.,   0.,   1.,   0.,  54.],
       [103.,   1.,   1.,   0.,   0.,   0.,  46.],
       [101.,   0.,   1.,   1.,   0.,   0.,  15.],
       [100.,   0.,   1.,   0.,   0.,   0.,  11.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  72.],
       [101.,   0.,   1.,   1.,   0.,   0.,  19.]])

In [59]:
X_train_transformed.shape

(80, 7)

In [62]:
transformer.transform(X_test)

array([[100.,   0.,   1.,   0.,   1.,   0.,  55.],
       [104.,   0.,   0.,   0.,   0.,   0.,  18.],
       [101.,   1.,   0.,   1.,   0.,   0.,  34.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [ 99.,   0.,   0.,   0.,   0.,   0.,  22.],
       [101.,   0.,   1.,   0.,   1.,   0.,  82.],
       [104.,   0.,   0.,   0.,   1.,   0.,  17.],
       [101.,   0.,   1.,   0.,   0.,   1.,  23.],
       [100.,   1.,   0.,   0.,   1.,   0.,  13.],
       [ 98.,   1.,   1.,   0.,   0.,   1.,  23.],
       [101.,   1.,   0.,   0.,   0.,   1.,  20.],
       [ 99.,   1.,   0.,   0.,   0.,   0.,  49.],
       [ 98.,   0.,   0.,   0.,   0.,   1.,  65.],
       [ 98.,   1.,   1.,   0.,   1.,   0.,  34.],
       [100.,   1.,   0.,   0.,   1.,   0.,  11.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  26.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [101.,   1.,   0.,   0.,   0.,   1.,  34.],
       [100.,   1.,   0.,   0.,   0.,   0.,  19.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  81.]])

In [61]:
transformer.transform(X_test).shape

(20, 7)